# Docker Compose override for MetaTrader5 Wine development
# 
# NOTE: MT5 functionality is now included in the main docker-compose.yml by default!
# This file is kept for reference and advanced customization.
#
# The main docker-compose.yml now includes:
# ✅ Wine 64-bit environment
# ✅ MT5 ports (1234 for rpyc, 5900 for VNC)  
# ✅ Wine environment variables
# ✅ Persistent wine data volumes
# ✅ Supervisord service management
#
# To use the main setup with MT5:
#   docker-compose up -d
#   docker exec -it algopy_app ./scripts/setup_mt5_wine.sh
#
# Advanced usage for development (optional overrides):
#   docker-compose -f docker-compose.yml -f docker-compose.mt5.yml up -d

version: "3.3"
services:
  app:
    environment:
      # Additional development settings
      - MT5_AUTO_START=true  # Override to auto-start MT5
      - MT5_DEBUG=true       # Enable debug logging
    # Additional development volumes (uncomment if needed)
    # volumes:
    #   - ./logs/mt5:/app/logs/mt5  # For MT5 log persistence